# Generated by Django 2.1.1 on 2019-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190720_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopting',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/'),
        ),
    ]
