# Generated by Django 2.1.1 on 2019-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_adopting_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopting',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
