# Generated by Django 2.1.1 on 2019-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190720_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopting',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/adopting'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/posting'),
        ),
    ]
