# Generated by Django 2.1.1 on 2019-07-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_school1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school1',
            name='v_url',
            field=models.FileField(upload_to='videos/person'),
        ),
    ]
