# Generated by Django 2.1.1 on 2019-07-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20190720_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school1',
            name='v_url',
        ),
    ]
