# Generated by Django 2.1.1 on 2019-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_school1_v_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopting',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='school1',
            name='url1',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
