# Generated by Django 2.1.1 on 2019-07-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20190721_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school1',
            name='url1',
            field=models.FileField(blank=True, upload_to='video/parent'),
        ),
    ]
