# Generated by Django 2.1.1 on 2019-07-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20190721_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school1',
            name='url1',
            field=models.URLField(blank=True),
        ),
    ]
