# Generated by Django 2.1.1 on 2019-07-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20190721_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school1',
            name='url1',
        ),
    ]
