# Generated by Django 2.1.1 on 2019-07-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_remove_school1_url1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School1',
            new_name='School',
        ),
    ]
