# Generated by Django 2.1.1 on 2019-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20190721_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='url1',
            field=models.ImageField(blank=True, upload_to='test'),
        ),
    ]
