# Generated by Django 2.1.1 on 2019-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_school_url1'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/revewing'),
        ),
    ]
