# Generated by Django 2.1.1 on 2019-07-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='url1',
        ),
        migrations.AddField(
            model_name='school',
            name='image3',
            field=models.ImageField(blank=True, upload_to='video/parent'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='title3',
            field=models.CharField(max_length=255),
        ),
    ]
