# Generated by Django 2.1.1 on 2019-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20190721_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopting',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/adopting'),
        ),
    ]
