# Generated by Django 2.1.1 on 2019-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_adopting_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='image3',
        ),
        migrations.AddField(
            model_name='school',
            name='url1',
            field=models.FileField(blank=True, upload_to='video/parent'),
        ),
    ]
