# Generated by Django 2.1.1 on 2019-07-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_auto_20190721_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='url1',
        ),
        migrations.AddField(
            model_name='school',
            name='file1',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
