# Generated by Django 2.1.1 on 2019-07-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20190721_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='url1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='file1',
            field=models.FileField(blank=True, upload_to='viedo/parent'),
        ),
    ]
