# Generated by Django 2.1.1 on 2019-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_remove_school_url1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='file1',
            field=models.FileField(null=True, upload_to='viedo/parent'),
        ),
    ]
