# Generated by Django 2.1.1 on 2019-07-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_school_url1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='School_parents',
        ),
    ]
