# Generated by Django 2.1.1 on 2019-07-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_school_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_parents',
            name='file1',
        ),
    ]
