# Generated by Django 2.1.1 on 2019-07-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_remove_school_parents_file1'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_dog',
            name='thumbnail2',
            field=models.ImageField(blank=True, upload_to='images/school'),
        ),
        migrations.AddField(
            model_name='school_parents',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/school'),
        ),
    ]
