# Generated by Django 2.1.1 on 2019-07-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0040_magazine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='title',
            new_name='name',
        ),
    ]
