# Generated by Django 2.1.1 on 2019-08-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0041_auto_20190729_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
